name: Test Gamma

on:
  workflow_call:
    inputs:
      ldc_compiler_version:
        type: string
        required: true
      gamma_used_dmd_compiler_version:
          type: string
          required: false
          default: "dmd-2.103.1"
      build_type:
        type: string
        required: false
        default: "debug"
  
jobs:
  test:
    name: Test Gamma
    strategy:
      matrix:
        os: [Windows, Linux, MacOS]
        include:
          - os: Windows
            runner: windows-latest
          - os: Linux
            runner: ubuntu-latest
          - os: MacOS
            runner: macOS-latest

    runs-on: ${{ matrix.runner }}
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Install D compiler for building gamma
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ inputs.ldc_compiler_version }}
    
    - name: Install DMD compiler if not installed yet, called by gamma during unittests
      uses: dlang-community/setup-dlang@v1
      with:
        compiler: ${{ inputs.gamma_used_dmd_compiler_version }}
    
    - name: Run tests
      run: |
        dub build --compiler=ldc2 --build=${{inputs.build_type}}
        dub test --compiler=ldc2 --build=unittest --config=example

